### ISSUE TITLE
dRAGon Development Mode : Continuous Java Build

### ISSUE THREAD

**Issue by amengus87** [dRAGon-Okinawa/docs#1]
# 1. Launch only the Backend API server and the Job Server :
`gradle bootRun -x :frontend:pnpmBuild -x :backend:copyWebApp`

# 2. Open your browser at http://localhost:1985/api/swagger-ui.html to access the Backend API server

# 3. Enable Continuous Java Build :
`gradle backend:bootJar -continuous -xtest -x :frontend:pnpmBuild -x :backend:copyWebApp`

**Comment by isontheline** [comment]
Done : https://docs.dragon.okinawa/contributing/dragon-development-mode
